In [1]:
my_1d_list=[1,2,3,4]
print(my_1d_list)

[1, 2, 3, 4]


In [10]:
open(
    my_file=open('numbers','a')  #Task 1    
    my_file.write(str('3 45 83 21')
)   my_file.close()
       

my_file.close()

SyntaxError: invalid syntax (Temp/ipykernel_10140/1408950372.py, line 3)

In [14]:
grade=int(input("what is your target grade?: " )) #Task 2
if grade >80 and grade <100:
        print ( "Grade A, Excellent work!")
elif grade >60 and grade <80:
        print ("Grade B,Well done!") 
elif grade >40 and grade <60:
        print ( "Grade C,Good try,work harder next time")
else:
        print ("Bad luck,you failed!")

Grade A, Excellent work!


In [17]:
grade=int(input("what is your percentage mark?: ")) #Task 2 Extension
def mark_grade (A ):
    if mark_grade >80:
      print(mark_grade ("well done!"))

In [14]:
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])
print(newArray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
import numpy as np
array = np.array([1,2,3,4,5,6,7,8,9])
newArray=array.reshape(3,3)
print(newArray) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
import numpy as np
odd = np.arange(10)
print(odd)

[0 1 2 3 4 5 6 7 8 9]


In [27]:
import numpy as np 
odd=np.arange(10)
print (odd) 
print ("subtract:",odd -1)


[0 1 2 3 4 5 6 7 8 9]
subtract: [-1  0  1  2  3  4  5  6  7  8]


In [34]:
import numpy as np
array = np.array([1, 2, 3, 4])
newArray = array.reshape(2, 2) 
print(newArray)





[[1 2]
 [3 4]]


In [39]:
import numpy as np
a = np.arange (0,9).reshape (3,3) 
b = np.arange (9,18).reshape (3,3) 
c = np.dot(a, b)
sum = np.sum(c) 
print(sum)

1458
